/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "#000",
        "text-100": "#fff",
        lavender: "#e7e8f2",
        slategray: "#7a7e92",
        "dark-blue-1-8": "#789ade",
        "blue-1-9": "#c8d3f9",
        darkblue: "#5811b0",
        honeydew: "#eaf8e4",
        lightgreen: "#91de85",
        "background-color-1": "#31353f",
        stroke: "#e4e4e4",
        "background-color-2": "#1b2028",
        "text-10": "#9e9e9e",
        "secondary-100": "#1ecb4f",
        "main-linear": "#3a6ff8",
        gainsboro: "#d9d9d9",
        "sec-100": "#f46d22",
        "primary-main-color": "#3377ff",
        "primary-light": "#fbfbfd",
        "dark-dark-3": "#8f90a6",
        "primary-lighter": "#99bbff",
        darkslategray: {
          "100": "#404b52",
          "200": "#3d3c42",
          "300": "#3a3a3c",
          "400": "#292d32",
        },
        silver: "#b5b7c0",
        blueviolet: "#5932ea",
        whitesmoke: {
          "100": "#f5f5f5",
          "200": "#eee",
        },
        darkgray: "#acacac",
        crimson: "#d0004b",
        forestgreen: "#00ac4f",
        gray: "#7e7e7e",
        ghostwhite: "#f9fbff",
        pink: "#ffc5c5",
        red: "#df0404",
        mediumaquamarine: "rgba(22, 192, 152, 0.38)",
        mediumseagreen: "#00b087",
        seagreen: "#008767",
      },
      spacing: {},
      fontFamily: {
        "space-grotesk": "'Space Grotesk'",
        "antic-slab": "'Antic Slab'",
        "droid-sans": "'Droid Sans'",
        antonio: "Antonio",
        nunito: "Nunito",
        "dm-sans": "'DM Sans'",
        larsseit: "Larsseit",
        "anonymous-pro": "'Anonymous Pro'",
        electrolize: "Electrolize",
        "overpass-mono": "'Overpass Mono'",
        "heading-2-20": "Poppins",
      },
      borderRadius: {
        "6xl": "25px",
        xl: "20px",
        "61xl": "80px",
        "3xs": "10px",
        mini: "15px",
        "8xs": "5px",
        "30xl": "49px",
        "10xs": "3px",
        "56xl": "75px",
        "99980xl": "99999px",
        "11xl": "30px",
      },
    },
    fontSize: {
      xl: "1.25rem",
      "45xl": "4rem",
      "13xl": "2rem",
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      "9xl": "1.75rem",
      "5xl": "1.5rem",
      "2xl": "1.313rem",
      "3xs": "0.625rem",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
